config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root 'products#index'


    resources :products
    resources :members
    resources :seasons

    post '/update_content', to: "products#update_content"
    post '/update_stock', to: "products#update_stock"
    post '/begin_checkout', to: "products#begin_checkout"
    post '/review', to: "products#begin_review"
    post '/confirm', to: "products#confirm"
    post '/send_message', to: "products#submit_contact"
    post '/delete_product', to: "products#delete_product"
    post '/delete_image', to: "products#delete_image"
    post '/delete_background_image', to: "products#delete_background_image"

    post '/add_to_cart', to: "products#add_to_cart"
    post '/remove_cart_item', to: "products#remove_cart_item"
    post '/update_tracking_number', to: "products#update_tracking_number"
    post '/update_background_video', to: "products#update_background_video"
		post '/auth_user', to: "products#auth_user"


    post '/login', to: "members#login"
    post '/enter_raffle', to: "members#enter_raffle"

		get '/login', to: "members#login"
    get '/logout', to: "members#logout"
    get '/raffle', to: "members#raffle"

    get '/member_list', to: "members#member_list"
    get '/about', to: "products#about"
    get '/return', to: "products#return"

    get '/content', to: "products#content"
    get '/get_size_info', to: "products#get_size_info"
    get '/get_cart_items', to: "products#get_cart_items"
    get 'stock/:product_id', to: "products#get_stock"
    get 'checkout', to: "products#checkout"
    get 'review', to: "products#review"
    get 'confirmation', to: "products#confirmation"
    get 'thanks', to: "products#thanks"
    get 'all', to: "products#all"
    get '/contact', to: "products#contact"
    get '/message_received', to: "products#after_contact"
    get '/pending_orders', to: "products#pending_orders"
    get '/pending_orders/:order_id', to: "products#show_pending_order"
    get 'stock', to: "products#get_all_stock"
    get '/change_background_video', to: "products#change_background_video"
    get '/get_background_video', to: "products#get_background_video"
    get '/launch', to: "products#launch"

    get 'lookbook', to: "seasons#lookbook"
    get '/seasons/:id/new-collection', to: "seasons#new_collection"
    get '/seasons/:id/collections/:collection_id', to: "seasons#show_collection"
    get '/seasons/:id/collections/:collection_id/new-collection-item', to: "seasons#new_collection_item"
    post '/save-collection', to: "seasons#save_collection"
    post '/save-collection-item', to: "seasons#save_collection_item"


end

app/models/product.rb
class Product < ApplicationRecord
	has_many_attached :images
	has_many :stocks


	def avail_sizes
		sizes = []
		stock_sizes = self.stocks.order(:size_value).select(:size)

		stock_sizes.each do |stock|

			if !sizes.include?(stock.size)
				sizes.push(stock.size)

			end;

		end

		return sizes

	end

	def stock_info()
		stocks = self.stocks.order(:size_value)
		stock_info = []

		stocks.each do |stock|
			stock_info.push([stock.size,stock.amount])
		end

		return stock_info
	end

	def sold_out
		return !(self.stocks.where("amount > ?", 0).count > 0)
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	skip_before_action :verify_authenticity_token, :only => [:delete_image, :delete_background_image, :add_to_cart, :get_cart_items, :remove_cart_item]

	before_action :check_buyer_params, :only =>[:confirm]


	include ActionView::Helpers::NumberHelper
	def index

		@landing_title = "" 

		if TitleContent.all.count > 0 
			@landing_title = TitleContent.last.landing_collection_title
		end 
		if(cookies[:is_admin])
			@products = Product.where(is_deleted: false, is_front_page: true).order(hidden: :desc, is_members_only: :desc)
		else
			@products = Product.where(is_admin: false, is_deleted: false, is_front_page: true ).order(hidden: :desc, is_members_only: :desc)
		end

		@bg_images = BackgroundImage.all


	end



	def login
	end

	def content 
		check_is_admin()
		if TitleContent.all.count > 0 
			@content = TitleContent.last 
		else 
			@content = TitleContent.new 
		end 

		@bg_images = BackgroundImage.all
	end

	def update_content
		check_is_admin()
		landing_title = params["landing_title"]
		shop_title = params["shop_title"]	
		image = params["images"]

		if TitleContent.all.count > 0 
			content = TitleContent.last 
			content.update_attribute(:landing_collection_title, landing_title)
			content.update_attribute(:shop_collection_title, shop_title)
		else 
			TitleContent.create(:landing_collection_title => landing_title, :shop_collection_title => shop_title)
		end 


		if image != nil
			bg_img = BackgroundImage.create()
			bg_img.image.attach(image)
		end

		redirect_to "/content"

	end 

	def launch
	end

	def auth_user

		email = params["email"]
		password = params["password"]

		if(email == "tomi@uglimyclothes.com" && password == "trussbruv")
			cookies[:is_admin] = true
			redirect_to "/stock"
		else
			redirect_to "/"
		end

	end

	def change_background_video
		check_is_admin()
		@videos = BackgroundVideo.where(:is_current => true)
	end

	def update_background_video
		BackgroundVideo.where(:is_current => true).update_all(:is_current => false)
		background_video = BackgroundVideo.new
		mobile_video = params["mobile_video"]
		desktop_video = params["desktop_video"]
		background_video.videos.attach(desktop_video)
		background_video.videos.attach(mobile_video)
		background_video.update_attribute(:is_current,true)
		background_video.save
		redirect_to "/products"


	end

	def get_background_video

		device = params["device"]
		video = BackgroundVideo.where(is_current: true).first
		if device == "desktop"
			video = video.videos.first
		elsif device == "mobile"
			video = video.videos.last
		end

		render status: 200, json:
		{
			video: url_for(video)
		}.to_json

	end

	def all
		@shop_title = "" 

		if TitleContent.all.count > 0 
			@shop_title = TitleContent.last.shop_collection_title
		end 

		if(cookies[:is_admin])
			@products = Product.where(is_deleted: false).order(:rank, hidden: :desc, is_members_only: :desc)
		else
			@products = Product.where(is_admin: false, is_deleted: false).order(:rank, hidden: :desc, is_members_only: :desc)
		end
	end

	def show
		@product = Product.find(params[:id])

		if((@product.is_admin && !cookies[:is_admin]) || @product.hidden)
			redirect_to "/"
		end
		
		# @sizes = @product.avail_sizes
		@sizes = ["S","M","L"]


	end

	def add_to_cart

		if session[:cart] == nil || session[:cart].count == 0
			session[:cart] = {}
			session[:start] = Time.now
		end

		if !session[:cart].has_key?(params[:product_id])
			product = Product.find(params[:product_id])
			session[:cart][product.id] = {:size => params[:size]}

			session[:total] = session[:total].to_f + product.price
			render status: 200, json:
			{
				added: true,
				cart_length: session[:cart].count,
				product: product,
				image: url_for(product.images.order(:order_num).first),
				size: params[:size],
				total: session[:total]

			}.to_json
		else
			render status: 200, json:
			{
				added: false,
				message: "Due to high demand this can only be bought once"

			}.to_json

		end

	end

	def remove_cart_item
		session[:cart].delete(params[:product_id])
		product = Product.find(params[:product_id])

		session[:total] = session[:total].to_f - product.price

		render status: 200, json:
		{

			cart_length:session[:cart].count,
			total: session[:total]

		}.to_json

	end

	def get_size_info

		product_id = params[:product_id]
		size = params[:size]

		sold_out = true 

		stock = Stock.where( product_id: product_id, size: size )

		if stock.count > 0	 
			sold_out = !(stock.first.amount > 0)
		end 

		render status: 200, json:
		{
			sold_out: sold_out
		}.to_json

	end 

	def get_cart_items

		if session[:cart] != nil
			if session[:start] == nil || session[:start] < Time.now - 60 * 30
				clear_user_cart_info()
			else
				session[:start] =  Time.now
			end
		end

		cart = session[:cart]
		products = []
		active_storage_disk_service = ActiveStorage::Service::DiskService.new(root: Rails.root.to_s + '/storage/')
		total = 0
		if cart != nil
			cart.each do |product_id, cartItem|
				size = cartItem["size"]

				product = Product.find(product_id)

				total +=  product.price
				products.push({
							product: product,
							image: url_for(product.images.order(:order_num).first),
							size: size
						})
			end

		end

		session[:total] = total


		render status: 200, json:
		{

			products: products,
			total: total

		}.to_json


	end


	def begin_review
		

	end

	def new
		check_is_admin()
	end


	def create
		check_is_admin()

		@product = Product.new(product_params)
		if @product.save
			redirect_to "/stock"
		else
			@messages = @product.errors
			render action: :new
		end

	end
	def get_all_stock

		check_is_admin()
		@products = Product.all
	end

	def get_stock
		check_is_admin()

		@product = Product.find(params[:product_id])
		@stock = Stock.new

	end


	def update_stock
		check_is_admin()
		amount = params[:amount]
		size = params[:size]
		name = params[:name]
		style = params[:style]
		price = params[:price]
		link = params[:link]
		rank = params[:rank]

		product = Product.find(params[:product_id])

		is_admin = params.has_key?("is_admin")
		is_deleted = params.has_key?("is_deleted")
		is_members_only = params.has_key?("is_members_only")
		is_hidden = params.has_key?("hidden")
		is_front_page = params.has_key?("is_front_page")
		is_linked = params.has_key?("is_linked")


		description =  params[:description]
		product.update_attribute(:price, price)
		product.update_attribute(:name, name)
		product.update_attribute(:name, name)
		product.update_attribute(:style, style)
		product.update_attribute(:link, link)
		product.update_attribute(:rank, rank)

		product.update_attribute(:is_admin, is_admin)
		product.update_attribute(:is_deleted, is_deleted)
		product.update_attribute(:description, description)
		product.update_attribute(:is_members_only, is_members_only)
		product.update_attribute(:hidden, is_hidden)
		product.update_attribute(:is_front_page, is_front_page)
		product.update_attribute(:is_linked, is_linked)


		images = product.images
		new_images = params["images"]

		images.each do |image|
			new_image_order = params["image-"+image.id.to_s]
			image.update_attribute(:order_num, new_image_order)

		end


		if new_images != nil
			product.images.attach(new_images)
		end

		existing_stock = product.stocks.where(size: size).first

		if existing_stock != nil
			existing_stock.update_attribute(:amount, amount)
		else
			size_val = 0
			case size
			when "S"
			  size_val = 1
			when "M"
			  size_val = 2
			when "L"
				size_val = 3
			when "XL"
				size_val = 4
			end

			#if the user does not update the sizes
			if size_val > 0
				Stock.create(:size => size, :amount => amount, :product_id => product.id, :size_value => size_val)
			end

		end

		redirect_to "/stock/"+product.id.to_s


	end

	def review
		check_is_admin()

		@products = []
		session[:cart].each do |product_id, cart_item|

			product = Product.find(product_id)
			@products.push({:product =>  product, :size => cart_item["size"]

				})

		end

		if cookies[:member_id]
			@member = Member.find(cookies[:member_id])
		end


	end

	def confirm
	 	shipping = Ugli::SHIPPING_COST
		
		if cookies[:member_id]
			member.update_attribute(:address, session[:address])
			member.update_attribute(:state, session[:state])
			member.update_attribute(:zip, session[:zip])
			member.update_attribute(:city, session[:city])
			member.update_attribute(:name, session[:name])
		end

		# Stripe.api_key = "sk_test_WClc2JMNTyOv6wqCVqLrpvcL00l7JKuoYX"
		Stripe.api_key = "sk_live_Kw73lufNyf4XIRsE5UeqPkD000XISDZZlz"

		tax_cost = (session[:total].to_f * Ugli::STATE_TAX_COST).round(2)

		price = (( tax_cost + shipping + session[:total].to_f).round(2) * 100).to_i

		card_string = params[:brand] + " **** " + params[:last4]

		charge = Stripe::Charge.create({
		    amount: price,
		    currency: 'usd',
		    description: 'Ugli Clothing Charge',
		    source: params[:stripeToken],
		})

		buyer_address = params[:buyer_address]

		if params[:buyer_apt].length > 0 
			buyer_address = buyer_address + " Unit: " + params[:buyer_apt]
		end 

	if charge[:paid]
		if cookies[:member_id]
			order = Order.create(:name => params[:buyer_name],
						:email => params[:buyer_email],
						:address => buyer_address,
						:state => params[:buyer_state],
						:city => params[:buyer_city],
						:card => card_string,
						:zip => params[:buyer_zip],
						:items => session[:cart],
						:member_id => cookies[:member_id]

						)
		else
			order = Order.create(:name => params[:buyer_name],
						:email => params[:buyer_email],
						:address => buyer_address,
						:state => params[:buyer_state],
						:city => params[:buyer_city],
						:card => card_string,
						:zip => params[:buyer_zip],
						:items => session[:cart],
						)

		end

			detract_stock()

			UserMailer.purchase_email(
									:name => params[:buyer_name],
									:email => params[:buyer_email],
									:address => buyer_address,

app/views/products/after_contact.html.erb
<style type="text/css">
	*{
				font-family: 'Permanent Marker', cursive;

	}

	.container{
		display:flex;
		flex-direction:column;
		align-items: center; 
		padding-left:8%;
		padding-right:5%;
		padding-top:30vh;
		height:100vh;

	}

	.ugli-button{
		width:200px;
		margin-top:30px;
	}

</style>
<%=  render "nav" %>

<body> 
<section class="thanks-container"> 
	<div class="container"> 
		<h1> Message Received ! </h1>
		<span> 
			I will get back to you very soon ! - Tomi  
		</span>
		<a href="/products" > 
			<button type="submit" class="btn btn-primary ugli-button">Keep Shopping	</div>

</section>
</body>

	<%=  render "footer" %>

app/views/products/change_background_video.html.erb
<%= form_tag update_background_video_path, :class => "form",  multipart: true  do   %> 
		<%= file_field_tag "desktop_video", direct_upload: true %>
		<%= file_field_tag "mobile_video", direct_upload: true %>

 	   <%= submit_tag nil, class: "submit-button btn btn-primary" %>


<% end %> 

<h1> <%= @videos.count %> </h1>

app/views/products/contact.html.erb
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;800&display=swap" rel="stylesheet">

<style> 
	.contact-form-container{
		display: flex; 
		flex-direction: column;
		margin-top:10px; 
		padding-left:10px; 
		padding-right:10px; 
	}

	.contact-form, .contact-message{
		margin-top:20px;

	}

	.contact-message{
		height:300px !important;
	}

	.btn-send{
		margin-top: 30px;
		background-color: #252121;
		color: white;
		font-family: 'Lato', sans-serif;
		font-weight: 800;
		width: 181px;
		height: 42px;
		align-self: center;
	}

	.field{
		border: 0;
		outline: 0;
		background: transparent;
		border-bottom: 4px solid black;
		margin-top:26px; 
	}
	.message-field{
		background: transparent;
		border: 4px solid black;
		margin-top:16px; 
		border-radius:5px;
		height:300px; 
		margin-top:26px; 

	}

	::placeholder {
		color: black;
		font-size: 20px;
		font-weight: bold; 
	  }
	  
	.contact-header{
		font-family: 'Lato', sans-serif;
		font-weight: 800;
		font-size: 33px;
		align-self: center;
	}

	.contact-info-container{
		display:flex; 
		flex-direction:column; 
		margin-top: 45px;
		padding-bottom:30px;    
	}

	.contact-us{
				font-family: 'Lato', sans-serif;
		font-weight: 800;
		font-size: 33px;
		align-self: center;
	}

	.email-info{
		font-family: 'Lato', sans-serif;
		font-weight: 800;
		font-size: 25px;
		margin-left: 40px;
		margin-top: 17px;
	}


	@media (min-width: 720px) {

		.contact-container{
			display:flex; 
			flex-direction:row; 
			justify-content:space-around; 
			padding-left:5%; 
			padding-right:5%; 
		}

		.contact-form-container{
			width:65%; 
		}


		.contact-info-container{
			width:25%; 
		}

		.btn-send{
			align-self:flex-start; 
		}

	}

</style>
<%=  render "nav" %>
	
	<body>
		<div class="content">
			<div class="contact-container">
				<%= form_tag send_message_path, :class => "contact-form-container"  do   %> 
					<span class="contact-header"> Contact </span> 

					<input name="name" class="field" type="text" placeholder="Your name" >


					<input name="email" class="field" type="text" placeholder="E-mail" >


					<input name="subject" class="field" type="text" placeholder="Subject" >

					<textarea name="message" class="message-field" placeholder="Message"></textarea>

					<button type="submit" class="btn btn-large btn-send">Send Message</button>



				<% end %> 

				<div class="contact-info-container">
					<span class="contact-header"> Contact Us </span> 
					<span class="email-info"> Email: </span>
					<span class="email-info"> info@uglimyclothes.com </span> 

				</div>
			</div>
		</div>

	</body>


<%=  render "footer" %>

app/views/products/get_all_stock.html.erb
<style>
	.product-image{
		width:300px;
		height:301px;
	}
</style>
<a href="/change_background_video" > Update Background video ? </a>
<br />
<% @products.each do |product| %>
	<a href="/stock/<%= product.id %>">
		<%if product.images.attached?  %>
			<%= image_tag product.images.first, class:"product-image "  %>
		<% end %>
	</a>

<% end %>

app/views/products/get_stock.html.erb
<style> 

	.form{
		display: flex; 
		flex-direction: column; 
		width:400px;
		margin-left:25%;
		margin-top: 5%; 
	}
	.images{
		display: flex; 
		flex-direction: row; 

	}

	.image{
		width:100px;
		height:100px;
	}

	.image-container{
		display: flex; 
		flex-direction: column; 
		width:200px;
		align-items: center;

	}

	.delete-button{
		margin-bottom:10px;
	}

	.order-form{
		width:30px;
		height: 20px; 
	}

	.size-container{
		display: flex; 
		flex-direction: row; 
		margin-top:30px;
	}

	.size-container input{
		width:100px;
		margin-right:30px;
		margin-bottom: 30px; 

	}

	.submit-button{
		margin-top:30px;
	}

	textarea{
		min-height:500px ; 
		min-width:500px; 
	}

</style>
<%= @product.name %>
<%= form_tag update_stock_path, :class => "form",  multipart: true  do   %>


		<div class="images">

			<% @product.images.order(:order_num).each do |image| %>
				<div class="image-container">
					<%= image_tag image, class:"image" %>
					<span class="delete-button glyphicon glyphicon-remove" onclick="deleteImage(<%=@product.id%> ,<%=image.id%> )"> </span>
					<input name="image-<%=image.id%>" type="text" class="order-form" value="<%= image.order_num %>">
				</div>
			<% end %>
		</div>
		<span> Current Stock :

			<% @product.stock_info().each do |size,amount| %>
				<%= size %> <%= amount %>
			<% end %>

		</span>
		
		<div class="size-container">
			<%= text_field_tag "size" ,@stock.size , placeholder: "size", :class=> "form-control"%>
			<%= text_field_tag "amount" ,@stock.amount , placeholder: "Amount", :class=> "form-control"%>
		</div>
		<input name="name" placeholder="Name" value="<%= @product.name %>">
		<input name="style" placeholder="Style" value="<%= @product.style %>">
		<input name="price" placeholder="Price" value="<%= @product.price %>">
		<input name="rank" placeholder="Rank Order" value="<%= @product.rank %>">
		<input name="link" placeholder="Link" value="<%= @product.link %>">

		<textarea name="description" placeholder="Description" ><%= @product.description %> </textarea>

		<div>
			<label for="is_members_only"> Members Only ?  </label>
			<input type="checkbox" id="is_members_only" name="is_members_only" <%=@product[:is_members_only] ? "checked" : '' %>>
		</div>

		<div>
			<label for="is_deleted"> Is Admin ?</label>
			<input type="checkbox" id="is_admin" name="is_admin" <%=@product[:is_admin] ? "checked" : '' %>>
		</div>

		<div>
			<label for="is_deleted"> Soft Delete ?</label>
			<input type="checkbox" id="is_deleted" name="is_deleted" <%=@product[:is_deleted] ? "checked" : '' %>>
		</div>

		<div>
			<label for="hidden"> Coming Soon  ?</label>
			<input type="checkbox" id="hidden" name="hidden" <%=@product[:hidden] ? "checked" : '' %>>
		</div>

		<div>
			<label for="is_front_page"> Front Page  ?</label>
			<input type="checkbox" id="is_front_page" name="is_front_page" <%=@product[:is_front_page] ? "checked" : '' %>>
		</div>

		<div>
			<label for="is_linked"> Is External Purchase ?</label>
			<input type="checkbox" id="is_linked" name="is_linked" <%=@product[:is_linked] ? "checked" : '' %>>
		</div>


		<%= hidden_field_tag "product_id" , @product.id%>

		<%= file_field_tag "images", multiple: true, direct_upload: true %>



 	   <%= submit_tag nil, class: "submit-button btn btn-primary" %>

	<% end %>

	<script type="text/javascript">

		function post(path, params, method) {
		    method = method || "post"; // Set method to post by default if not specified.

		    // The rest of this code assumes you are not using a library.
		    // It can be made less wordy if you use one.
		    var form = document.createElement("form");
		    form.setAttribute("method", method);
		    form.setAttribute("action", path);

		    for(var key in params) {
		        if(params.hasOwnProperty(key)) {
		            var hiddenField = document.createElement("input");
		            hiddenField.setAttribute("type", "hidden");
		            hiddenField.setAttribute("name", key);
		            hiddenField.setAttribute("value", params[key]);

		            form.appendChild(hiddenField);
		        }
		    }

		    document.body.appendChild(form);
		    form.submit();
		}

		function deleteImage(productId, imageId){
			post('/delete_image', {product_id: productId, image_id: imageId});
		}


	</script>

app/views/products/launch.html.erb
<link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
<%= stylesheet_link_tag 'launch', media: 'all', 'data-turbolinks-track': 'reload' %>

<title>  High End Untraditional Clothing Styles and Colors | Ugli Done Beautifully </title>
<head>  <meta name="description" content="Shop Untraditional But Beautiful High End Hoodies, Shirts, Sweaters and More for Men, Women and, & Kids. Become a member for More Exclusive Clothing 
"></head>

<body>
    <section class="launch-section">
	    <a class="brand-name marker" href="#">Ugli</a>
        <span class="launch-header"> 
            Spring 
            Collection
            February 6th
        </span>

        <span class="thank-text">
            Thanks for the interest 
            on the new collection but 
            please comeback on the 6th 
            of February. 

            <br /> 
            <br />
            For now you can 
            <span class="important-text"> <br/> PRE-ORDER </span> the collection 
            <b> VIA</b> Ugli <b> DMs </b> 
        </span>

        <div class="landing-footer-icon-conainer-mobile">
                <img class="" src="<%=asset_path 'mail_transparent.png' %>" />
            <a target="_blank" class= "footer-link" href="https://www.instagram.com/uglimyclothes/" >
                <img class="" src="<%=asset_path 'ig_transparent.png' %>" />
            </a>
        </div>

    </section>

    <div class="landing-footer-desktop">
        <div class="landing-footer-text-container">
            <span>© Ugli 2020  </span>        
            <span> Terms of Serivce </span>  
            <span> Return Policy    </span>
        </div>
        
        <div class="landing-footer-icon-conainer">
                <img class="" src="<%=asset_path 'mail_transparent.png' %>" />
            <a target="_blank" class= "footer-link" href="https://www.instagram.com/uglimyclothes/" >
                <img class="" src="<%=asset_path 'ig_transparent.png' %>" />
            </a>

        </div>
    </div>

</body>

app/views/products/login.html.erb
<style>

	.contact-container{

		display: flex;
		flex-direction: column;
		margin-top:10px;
		padding-right:10%;
		padding-left:10%;

	}


	.contact-form, .contact-message{
		margin-top:20px;

	}

	.contact-message{
		height:300px !important;
	}

	.btn-send{
		margin-top:30px;
	}
</style>
<%=  render "nav" %>

	<body>
		<div class="content">
			<%= form_tag auth_user_path, :class => "contact-container"  do   %>

				<input name="email" class="form-control contact-form" type="text" placeholder="E-mail" >
        <input name="password" class="form-control contact-form" type="password" placeholder="Password" >

				<button type="submit" class="btn btn-primary btn-large btn-send">Send Message</button>
			<% end %>
		</div>

	</body>


<%=  render "footer" %>

app/views/products/show_pending_order.html.erb
<style> 
  .container{
    display: flex; 
    flex-direction: column; 
    padding-top:50px;
  }

</style>

<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />

  </head>
  <body>
    <%= form_tag update_tracking_number_path, :class => "container"  do   %> 

      <span> Buyer Info</span>
      <span class="divider"></span>

      <span> <%= @name %> </span>
      <span> <%= @full_address %> </span>

      <span> Order number: <%= @order.order_num %> </span>
      <span> Tracking Number: <%=@order.tracking_number ? @order.tracking_number : 'Not Set' %> </span>
      <span> Shpping Method: <%=@order.shipping_method ? @order.shipping_method : 'Not Set' %> </span>

       <span>Items description <span>

       
       <br>


      <% @products.each do |product_dic| %>

					<%= image_tag product_dic[:product].images.order(:order_num).first, class:"carousel-cell", height: "200px" %>
           <span>
              <%= product_dic[:product].name %> (<%= product_dic[:size] %>)
            </span>
            <span class="item-price">
              $<%= product_dic[:product].price %>
            </span>
            <br> 

      <% end %>



      <input name="tracking_number" class="form-control" type="text" placeholder="Tracking Number" value="<%=@order.tracking_number ? @order.tracking_number : '' %>"<>
      <select name="shipping_method" class="form-control" type="text" placeholder="" value="<%=@order.shipping_method ? @order.shipping_method : '' %>">
          <option> USPS</option>
          <option value="FEDEX"> FEDEX </option>
          <option> UPS</option>
      </select>

      <input name="order_id" type="hidden" value="<%= @order.id %> " >
        <button type="submit" class="btn btn-primary btn-large">Update Tracking Info </button>

    <% end %>
  </body>
</html>

app/views/products/thanks.html.erb
<style type="text/css">
	*{
    font-family: 'Lato', sans-serif;

	}

	.container{
		display:flex;
		flex-direction:column;
		align-items: center; 
		padding-top:30vh;
		height:100vh;

	}

	.ugli-button{
		width:200px;
		margin-top:30px;
		background-color:black; 
	}

	.tracking-text{
		align-self:center; 
		text-align:center;
		font-size:20px; 
	}

</style>
<%=  render "nav" %>

<body>
<section class="thanks-container">
	<div class="container">
		<h1> Thanks Ugli </h1>
		<span class="tracking-text"> 
			The tracking number will be sent to the email you provided when your product ships
		</span>
		<a href="/products" >
			<button type="submit" class="btn btn-primary ugli-button">Get Uglier</button>
		</a>
	</div>

</section>
</body>

	<%=  render "footer" %>