config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root 'products#index'


    resources :products
    resources :members
    resources :seasons

    post '/update_content', to: "products#update_content"
    post '/update_stock', to: "products#update_stock"
    post '/begin_checkout', to: "products#begin_checkout"
    post '/review', to: "products#begin_review"
    post '/confirm', to: "products#confirm"
    post '/send_message', to: "products#submit_contact"
    post '/delete_product', to: "products#delete_product"
    post '/delete_image', to: "products#delete_image"
    post '/delete_background_image', to: "products#delete_background_image"

    post '/add_to_cart', to: "products#add_to_cart"
    post '/remove_cart_item', to: "products#remove_cart_item"
    post '/update_tracking_number', to: "products#update_tracking_number"
    post '/update_background_video', to: "products#update_background_video"
		post '/auth_user', to: "products#auth_user"


    post '/login', to: "members#login"
    post '/enter_raffle', to: "members#enter_raffle"

		get '/login', to: "members#login"
    get '/logout', to: "members#logout"
    get '/raffle', to: "members#raffle"

    get '/member_list', to: "members#member_list"
    get '/about', to: "products#about"
    get '/return', to: "products#return"

    get '/content', to: "products#content"
    get '/get_size_info', to: "products#get_size_info"
    get '/get_cart_items', to: "products#get_cart_items"
    get 'stock/:product_id', to: "products#get_stock"
    get 'checkout', to: "products#checkout"
    get 'review', to: "products#review"
    get 'confirmation', to: "products#confirmation"
    get 'thanks', to: "products#thanks"
    get 'all', to: "products#all"
    get '/contact', to: "products#contact"
    get '/message_received', to: "products#after_contact"
    get '/pending_orders', to: "products#pending_orders"
    get '/pending_orders/:order_id', to: "products#show_pending_order"
    get 'stock', to: "products#get_all_stock"
    get '/change_background_video', to: "products#change_background_video"
    get '/get_background_video', to: "products#get_background_video"
    get '/launch', to: "products#launch"

    get 'lookbook', to: "seasons#lookbook"
    get '/seasons/:id/new-collection', to: "seasons#new_collection"
    get '/seasons/:id/collections/:collection_id', to: "seasons#show_collection"
    get '/seasons/:id/collections/:collection_id/new-collection-item', to: "seasons#new_collection_item"
    post '/save-collection', to: "seasons#save_collection"
    post '/save-collection-item', to: "seasons#save_collection_item"


end

app/models/member.rb
class Member < ApplicationRecord
  has_secure_password
  validates :password_confirmation, presence: false

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
		@member = Member.find(params[:id])
	end

	def new
		@member = Member.new
	end

	def create
		@member = Member.new(member_params)
		if @member.save
			cookies[:member_id] = @member.id
			redirect_to "/"
		else
			flash[:error] = "#{@member.errors.details}  "
			render action: :new
		end
	end

	def edit

		@member = Member.find_by_id(params[:id])

		if params[:id].to_i == session[:member].to_i
			@member = Member.find_by_id(params[:id])
		else
			redirect_to "/videos"
		end
	end

	def raffle 
		if cookies.has_key?(:member_id)
			@member = Member.find(cookies[:member_id])
		end 
	end 

	def enter_raffle

		member = Member.find(cookies[:member_id])
		ig = params[:instagram]
		size = params[:size]
		member.update_attribute(:instagram,ig)
		member.update_attribute(:size,size)
		redirect_to "/raffle"




	end 

	def logout
    cookies.delete :member_id
    cookies.delete :is_admin
		redirect_to "/"

	end

	def member_list 
		check_is_admin()
		@members = Member.all 
	end 

	def login
		@member = Member.new
		@error = false
		if params.key?("email") and params.key?("password")
      if(params[:email] == "tomi@uglimyclothes.com" && params[:password] == "trussbruv")
        cookies[:is_admin] = true
        redirect_to "/stock"
      else
  			@member = Member.find_by(email: params[:email])
  			if @member and @member.authenticate( params[:password])
          cookies[:member_id] = { value: @member.id, expires: 1.hour }
  			  redirect_to "/"
  			else
  				@member = Member.new
  				@member.email = params[:email]
  				@error = true
  				render action: :login
  			end
		  end
    end
	end

	private

	def check_is_admin
		if(!cookies[:is_admin] == true)
			redirect_to "/"
		end
	end

	def member_params
		params.require(:member).permit(:email,:password)

	end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_footer.html.erb
<style> 
html, body {
  height: 100%;
  margin: 0;
}
.content {
  min-height: 100%;
}

footer{

	display:flex;
	flex-direction: column; 
   	background-color: black;
	padding-bottom: 10px; 
	padding-top:10px;


}

.footer-logo-holder{
	color:white;
	font-size:15px;
	flex-grow: 1;
}

.footer-logo{
	font-family: 'Permanent Marker', cursive;

}

.info-links{
	padding-left:10%; 
}

.info-links a {
	color:white; 
	margin-right:5px; 
}

.icon-holder{
	display: flex;
    flex-direction: row;
    margin-top: 5px;
    width: 100%;
    padding-right: 10%;
    padding-left: 10%;
}

.footer-link{
	text-decoration: none; 
	color:white;
}

.footer-icon{
	font-size:23px;
	margin-left: 7px; 

}

@media (min-width: 720px) {

	footer{
		flex-direction:row; 
		justify-content:space-between; 
	}

	.info-links{
		min-width:300px; 
	}

	.icon-holder{
		width:auto 
	}
	.footer-logo-holder{
		flex-grow: 0;
		padding-right:50px; 
	}


}


</style>
<footer>

	<div class="info-links">
		<a href="/about"> About </a>
		<a href="/return"> Return Policy </a>

	</div>
	<div class="icon-holder"> 

		<div class="footer-logo-holder"> 
			<span> © </span>
			<span class="footer-logo">Ugli</span>
			<span>2019 </span>
		</div>

		<a target="_blank" class= "footer-link" href="https://www.instagram.com/uglimyclothes/" >
			<i class="fab fa-instagram footer-icon" id="icon-insta"></i>
		</a>
		<a class= "footer-link" href="/contact" > 
			<i class="far fa-envelope footer-icon"></i> 
		</a>

	
	</div>

</footer>

app/views/members/login.html.erb
<%=  render "nav" %>
<%= stylesheet_link_tag "login", media: "all" %>

<section class="page-container">

  <%= form_tag login_path, :class => "member-login-container"  do   %>
    <% if @error %>
      <span class="error-text"> membername or Password provided Incorrect </span>
    <% end %>

    <div class="login-container" >
      <span class="form-header"> Login </span>
      <%= text_field_tag "email" ,@member.email,class: "field ",placeholder: 'Email'%>
      <%= password_field_tag "password" ,nil,class: " field ",placeholder: 'Password'%>

      <%= submit_tag "Sign In", class: "btn btn-primary login-button" %>
      <a href="#" class="forgot-link"> Forgot Your password ? </a>

    </div>
  <% end %>

    <%= form_for @member, html: {  class: ""} do |f|  %>

      <% if @member.errors.count > 0 %>
            <% @member.errors.each do |type,message|  %>
              <div class="error"> <%= type.capitalize %> <%= message %> 	</div>
            <% end%>
      <% end %>

      <div class="create-container">
      <span class="form-header" > Create Account </span>

        <%= f.text_field :email ,   :placeholder =>' First Name',class: "field " %>
        <%= f.text_field :email ,   :placeholder =>' Last Name',class: "field " %>
        <%= f.text_field :email ,   :placeholder =>' Email',class: "field " %>
        <%= f.password_field :password ,   :placeholder =>'Password',class: "field" %>

        <%= f.submit "Sign Up ",class: "btn btn-primary login-button" %>

      </div>

    <% end %>

</section>

app/views/members/member_list.html.erb
<% @members.each do |member| %>
    <div>
       <span> Email: </span>  <%= member.email %> <%= member.created_at.strftime("%m/%d/%Y %T") %>
        <br> 
        <% if member.instagram %>
           <b> instagram </b> <%= member.instagram %>
        <%end %>

     </div>
<% end %>

app/views/members/new.html.erb
<%=  render "nav" %>
<%= stylesheet_link_tag "login", media: "all" %>



<%= form_for @member, html: {  class: "member-login-container"} do |f|  %>
	<img class="login-logo" src="<%=asset_path 'ugli_abridged.png' %>" />

	<% if @member.errors.count > 0 %>
				<% @member.errors.each do |type,message|  %>
					<div class="error"> <%= type.capitalize %> <%= message %> 	</div>
				<% end%>
	<% end %>

  <div class="fields" >

	  <%= f.text_field :email ,   :placeholder =>' Email',class: "form-control form-control-lg field " %>

		<%= f.password_field :password ,   :placeholder =>'Password',class: "form-control form-control-lg field" %>
 	   <%= f.submit "Register ",class: "btn btn-primary login-button" %>

 	</div>

	<%= link_to "Login", login_path %>



	<% end %>

app/views/members/raffle.html.erb
<style> 
    .raffle-body{
        display:flex; 
        flex-direction:column; 
        align-items:center; 
        margin-top:20vh; 
    }

    .step{
        font-size:21px; 
        text-align:center; 
        margin-top:10px; 
    }

    .entered-text{
        font-size:20px; 
        max-width:70vh; 
        text-align:center; 
    }

    input, select {
        margin-top:15px; 
    }

    .raffle-btn {
        width:200px; 
        margin-top:15px; 
    }

</style>

<%=  render "nav" %>
    <div class="content raffle-body">


        <%if cookies.has_key?(:member_id) && @member.instagram != nil %>
            <span class="entered-text"> 
                You have entered the raffle. <br /> If you are selected we <br> will message you on instagram !
            </span> 
        <% else %>
        <h3> Steps To Enter Raffle </h3>
                <%if !cookies.has_key?(:member_id) %>
                    <a href="/members/new" class="step"> <span class="step-num"> 1. </span> Become a Member. Click Here </a>
                <% end %>
                <div class="step"> <span class="step-num"> 2. </span> Follow Us On Instagram <a href="https://www.instagram.com/uglimyclothes/" > @uglimyclothes </a> </div>
                <div class="step"> <span class="step-num"> 3. </span> Fill Out Information Below </div>
                <%= form_tag "/enter_raffle", :class => "raffle-input-container" do   %>
                    <input class="form-control" name="instagram" type="text" placeholder="Instagram Handle">
                    <select name="size" class="form-control" placeholder="">
                            <option value="" disabled selected hidden>Size</option>
                            <option> S</option>
                            <option> M</option>
                            <option> L</option>

                    </select>
                
                    <button class="raffle-btn btn btn-primary " type="submit"> Enter Raffle </button>
                <% end %>
        <% end %>
             </div>
    

<%=  render "footer" %>